apiVersion: v1
kind: Service
metadata:
  name: ticket-service
  labels:
    app: ticket-service
spec:
  selector:
    app: ticket-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
